[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
han_master_solana = "9JjymTUKnDM91mAx3g75yvMkxW8udrx16AfVkmRwjNjJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/star/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
